#!/usr/bin/env bash
# =============================================================================
#  vendor-assets.sh
#  Downloads the CDN assets the app used to fetch at runtime and stores them
#  locally in public/assets/ so the UI renders correctly with NO internet.
#
#  Needs internet. Run once; the files are then committed to the repo.
#
#  Replaces:
#    https://cdn.tailwindcss.com                  -> public/assets/tailwind.min.js
#    https://fonts.googleapis.com/css2?...Nunito  -> public/assets/nunito.css
#                                                  + public/assets/fonts/*.woff2
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")/.."
ASSETS="public/assets"
FONTS="${ASSETS}/fonts"
mkdir -p "$FONTS"

# Pinned so the design can't shift under you on a later rebuild.
TAILWIND_VERSION="3.4.16"
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

echo "--> Tailwind Play CDN v${TAILWIND_VERSION}"
curl -fsSL "https://cdn.tailwindcss.com/${TAILWIND_VERSION}" -o "${ASSETS}/tailwind.min.js"

echo "--> Nunito webfont (latin + latin-ext)"
curl -fsSL -A "$UA" \
  "https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700;800;900&display=swap" \
  -o /tmp/nunito-src.css

php -r '
$src = file_get_contents("/tmp/nunito-src.css");
$parts = preg_split("/\/\*\s*([a-z\-]+)\s*\*\//", $src, -1, PREG_SPLIT_DELIM_CAPTURE);
$keep = ["latin", "latin-ext"];
$ranges = [];
$urls = [];
for ($i = 1; $i < count($parts); $i += 2) {
    $label = $parts[$i]; $body = $parts[$i + 1];
    if (!in_array($label, $keep, true) || isset($ranges[$label])) continue;
    if (!preg_match("/url\((https:\/\/[^)]+\.woff2)\)/", $body, $m)) continue;
    preg_match("/unicode-range:\s*([^;]+);/", $body, $r);
    $urls[$label] = $m[1];
    $ranges[$label] = trim($r[1]);
}
foreach ($urls as $label => $url) {
    file_put_contents("public/assets/fonts/nunito-$label.woff2", file_get_contents($url));
    echo "    saved nunito-$label.woff2\n";
}
$css = "/* Nunito - self-hosted variable font (weights 400-900).\n"
     . "   Generated by scripts/vendor-assets.sh so the app needs NO internet.\n"
     . "   Do not edit by hand. */\n";
foreach (["latin-ext", "latin"] as $label) {
    if (!isset($ranges[$label])) continue;
    $css .= "\n/* $label */\n@font-face {\n"
          . "  font-family: \x27Nunito\x27;\n  font-style: normal;\n"
          . "  font-weight: 400 900;\n  font-display: swap;\n"
          . "  src: url(fonts/nunito-$label.woff2) format(\x27woff2\x27);\n"
          . "  unicode-range: {$ranges[$label]};\n}\n";
}
file_put_contents("public/assets/nunito.css", $css);
'

echo
echo "✔ Local assets ready:"
ls -la "$ASSETS"/tailwind.min.js "$ASSETS"/nunito.css "$FONTS"/*.woff2
