<?php
/**
 * includes/lettuce-catalog.php
 * ------------------------------------------------------------------
 * Product catalog for Luntiang H.A.P.A.G.
 * Hydroponic Harvest-on-Demand Lettuce Farm
 *
 * Products include single varieties, pack sizes, bundles, and wholesale.
 * Each product includes harvest-on-demand information.
 * ------------------------------------------------------------------
 */
return [
    // ---- SINGLE VARIETIES (Per Cup) ----
    [
        'name'       => 'Romaine Lettuce',
        'variety'    => 'Giulia NH & Grizzari NZ',
        'price'      => 45,
        'unit'       => 'per cup',
        'category'   => 'single',
        'bestSeller' => true,
        'image'      => 'images/lettuce/romaine-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Caesar salad, sandwiches, wraps',
        'calories'   => 17,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Batavia Lettuce',
        'variety'    => 'Graction NZ, Rijk Zwaan',
        'price'      => 40,
        'unit'       => 'per cup',
        'category'   => 'single',
        'bestSeller' => true,
        'image'      => 'images/lettuce/batavia-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Sandwiches, burgers, wraps, salads',
        'calories'   => 15,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Bianca Lettuce',
        'variety'    => 'Butterhead, NH',
        'price'      => 45,
        'unit'       => 'per cup',
        'category'   => 'single',
        'bestSeller' => true,
        'image'      => 'images/lettuce/bianca-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Lettuce wraps, delicate salads',
        'calories'   => 13,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Dabi Lettuce',
        'variety'    => 'Lollo Bionda, Frizz Zakken',
        'price'      => 40,
        'unit'       => 'per cup',
        'category'   => 'single',
        'bestSeller' => false,
        'image'      => 'images/lettuce/dabi-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Garnishes, mixed salads, plating',
        'calories'   => 14,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Red Lettuce',
        'variety'    => 'Lollo Rossa',
        'price'      => 42,
        'unit'       => 'per cup',
        'category'   => 'single',
        'bestSeller' => false,
        'image'      => 'images/lettuce/red-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Gourmet salads, colorful plating',
        'calories'   => 16,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Estrosa Lettuce',
        'variety'    => 'Lollo Bionda, Frizz Zakken',
        'price'      => 38,
        'unit'       => 'per cup',
        'category'   => 'single',
        'bestSeller' => false,
        'image'      => 'images/lettuce/estrosa-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Artisan salads, garnishes',
        'calories'   => 12,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Olmetie Lettuce',
        'variety'    => 'Batavia, Rijk Zwaan',
        'price'      => 48,
        'unit'       => 'per cup',
        'category'   => 'single',
        'bestSeller' => false,
        'image'      => 'images/lettuce/olmetie-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Chef-preferred, premium salads',
        'calories'   => 15,
        'harvestTime'=> '1-3 hours after order',
    ],

    // ---- PACK SIZES (Same variety, different quantities) ----
    [
        'name'       => 'Romaine Twin Pack',
        'variety'    => 'Giulia NH & Grizzari NZ · 2 Cups',
        'price'      => 85,
        'unit'       => 'per twin pack',
        'category'   => 'pack',
        'bestSeller' => false,
        'image'      => 'images/lettuce/romaine-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Small families, meal prep',
        'calories'   => 34,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Romaine Family Pack',
        'variety'    => 'Giulia NH & Grizzari NZ · 4 Cups',
        'price'      => 160,
        'unit'       => 'per family pack',
        'category'   => 'pack',
        'bestSeller' => true,
        'image'      => 'images/lettuce/romaine-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Family meals, weekly supply',
        'calories'   => 68,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Batavia Family Pack',
        'variety'    => 'Graction NZ · 4 Cups',
        'price'      => 145,
        'unit'       => 'per family pack',
        'category'   => 'pack',
        'bestSeller' => false,
        'image'      => 'images/lettuce/batavia-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Sandwich lovers, family meals',
        'calories'   => 60,
        'harvestTime'=> '1-3 hours after order',
    ],

    // ---- MIXED & SALAD ----
    [
        'name'       => 'Mixed Greens Cup',
        'variety'    => 'Butterhead + Lollo Rossa + Romaine',
        'price'      => 60,
        'unit'       => 'per cup',
        'category'   => 'mixed',
        'bestSeller' => false,
        'image'      => 'images/lettuce/mixed-greens.png',
        'shelfLife'  => 'Best consumed immediately when refrigerated',
        'bestFor'    => 'Instant colorful salads',
        'calories'   => 18,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Garden Salad Mix',
        'variety'    => 'Batavia + Estrosa + Red Leaf',
        'price'      => 65,
        'unit'       => 'per cup',
        'category'   => 'mixed',
        'bestSeller' => true,
        'image'      => 'images/lettuce/garden-salad.png',
        'shelfLife'  => 'Best consumed immediately when refrigerated',
        'bestFor'    => 'Restaurant-style garden salads at home',
        'calories'   => 20,
        'harvestTime'=> '1-3 hours after order',
    ],

    // ---- BUNDLES ----
    [
        'name'       => 'Family Bundle (4 cups + Dressing)',
        'variety'    => 'Assorted Cups + House Dressing',
        'price'      => 180,
        'unit'       => 'per bundle',
        'category'   => 'bundle',
        'bestSeller' => false,
        'image'      => 'images/lettuce/family-bundle.png',
        'shelfLife'  => '5-7 days refrigerated (dressing: 2 weeks)',
        'bestFor'    => 'Family dinner, 4 servings',
        'calories'   => 75,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Weekend Bundle (6 cups + Dressing + Wrap Kit)',
        'variety'    => 'Assorted Cups + Dressing + Wrap Kit',
        'price'      => 260,
        'unit'       => 'per bundle',
        'category'   => 'bundle',
        'bestSeller' => true,
        'image'      => 'images/lettuce/weekend-bundle.png',
        'shelfLife'  => '5-7 days refrigerated (dressing: 2 weeks)',
        'bestFor'    => 'Weekend gatherings, family of 4-6',
        'calories'   => 110,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Healthy Starter Bundle',
        'variety'    => '2 Romaine + 2 Bianca + Dressing',
        'price'      => 160,
        'unit'       => 'per bundle',
        'category'   => 'bundle',
        'bestSeller' => false,
        'image'      => 'images/lettuce/family-bundle.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'New to hydroponic lettuce, starter kit',
        'calories'   => 60,
        'harvestTime'=> '1-3 hours after order',
    ],
    [
        'name'       => 'Caesar Salad Bundle',
        'variety'    => '3 Romaine + Dressing + Croutons',
        'price'      => 170,
        'unit'       => 'per bundle',
        'category'   => 'bundle',
        'bestSeller' => false,
        'image'      => 'images/lettuce/romaine-lettuce.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Classic Caesar salads for the family',
        'calories'   => 65,
        'harvestTime'=> '1-3 hours after order',
    ],

    // ---- WHOLESALE ----
    [
        'name'       => 'Wholesale Tray (20 cups)',
        'variety'    => 'Assorted Varieties, Bulk Pack',
        'price'      => 700,
        'unit'       => 'per tray',
        'category'   => 'wholesale',
        'bestSeller' => false,
        'image'      => 'images/lettuce/wholesale-tray.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Resellers, canteens, small events',
        'calories'   => 300,
        'harvestTime'=> '2-4 hours after order (larger quantity)',
    ],
    [
        'name'       => 'Wholesale Box (50 cups)',
        'variety'    => 'Assorted Varieties, Bulk Pack',
        'price'      => 1650,
        'unit'       => 'per box',
        'category'   => 'wholesale',
        'bestSeller' => false,
        'image'      => 'images/lettuce/wholesale-tray.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Restaurants, events, large gatherings',
        'calories'   => 750,
        'harvestTime'=> '3-5 hours after order (larger quantity)',
    ],
    [
        'name'       => 'Restaurant Pack (10 cups)',
        'variety'    => 'Chef\'s Choice Assortment',
        'price'      => 380,
        'unit'       => 'per pack',
        'category'   => 'wholesale',
        'bestSeller' => false,
        'image'      => 'images/lettuce/garden-salad.png',
        'shelfLife'  => '5-7 days refrigerated',
        'bestFor'    => 'Small restaurants, cafés, food stalls',
        'calories'   => 160,
        'harvestTime'=> '2-3 hours after order',
    ],
];
